export const LANGUAGES = [
  { code: "ko", name: "한국어", label: "한국어 (Korean)" },
  { code: "en", name: "영어", label: "영어 (English)" },
  { code: "ja", name: "일본어", label: "일본어 (Japanese)" },
  {
    code: "zh-CN",
    name: "중국어(간체)",
    label: "중국어 간체 (Chinese Simplified)",
  },
  {
    code: "zh-TW",
    name: "중국어(번체)",
    label: "중국어 번체 (Chinese Traditional)",
  },
  { code: "vi", name: "베트남어", label: "베트남어 (Vietnamese)" },
  { code: "es", name: "스페인어", label: "스페인어 (Spanish)" },
  { code: "fr", name: "프랑스어", label: "프랑스어 (French)" },
  { code: "de", name: "독일어", label: "독일어 (German)" },
  { code: "id", name: "인도네시아어", label: "인도네시아어 (Indonesian)" },
  { code: "th", name: "태국어", label: "태국어 (Thai)" },
  { code: "ru", name: "러시아어", label: "러시아어 (Russian)" },
  { code: "pt", name: "포르투갈어", label: "포르투갈어 (Portuguese)" },
  { code: "it", name: "이탈리아어", label: "이탈리아어 (Italian)" },
  { code: "ar", name: "아랍어", label: "아랍어 (Arabic)" },
  { code: "hi", name: "힌디어", label: "힌디어 (Hindi)" },
  { code: "tr", name: "튀르키예어", label: "튀르키예어 (Turkish)" },
  { code: "nl", name: "네덜란드어", label: "네덜란드어 (Dutch)" },
  { code: "pl", name: "폴란드어", label: "폴란드어 (Polish)" },
  { code: "sv", name: "스웨덴어", label: "스웨덴어 (Swedish)" },
  { code: "cs", name: "체코어", label: "체코어 (Czech)" },
  { code: "hu", name: "헝가리어", label: "헝가리어 (Hungarian)" },
  { code: "ro", name: "루마니아어", label: "루마니아어 (Romanian)" },
  { code: "el", name: "그리스어", label: "그리스어 (Greek)" },
  { code: "ms", name: "말레이어", label: "말레이어 (Malay)" },
  { code: "fil", name: "필리핀어", label: "필리핀어 (Tagalog/Filipino)" },
  { code: "uk", name: "우크라이나어", label: "우크라이나어 (Ukrainian)" },
  { code: "he", name: "히브리어", label: "히브리어 (Hebrew)" },
  { code: "da", name: "덴마크어", label: "덴마크어 (Danish)" },
  { code: "fi", name: "핀란드어", label: "핀란드어 (Finnish)" },
  { code: "no", name: "노르웨이어", label: "노르웨이어 (Norwegian)" },
  { code: "bg", name: "불가리아어", label: "불가리아어 (Bulgarian)" },
  { code: "hr", name: "크로아티아어", label: "크로아티아어 (Croatian)" },
  { code: "sk", name: "슬로바키아어", label: "슬로바키아어 (Slovak)" },
  { code: "sl", name: "슬로베니아어", label: "슬로베니아어 (Slovenian)" },
  { code: "et", name: "에스토니아어", label: "에스토니아어 (Estonian)" },
  { code: "lv", name: "라트비아어", label: "라트비아어 (Latvian)" },
  { code: "lt", name: "리투아니아어", label: "리투아니아어 (Lithuanian)" },
  { code: "bn", name: "벵골어", label: "벵골어 (Bengali)" },
  { code: "ur", name: "우르두어", label: "우르두어 (Urdu)" },
  { code: "fa", name: "페르시아어", label: "페르시아어 (Persian)" },
  { code: "sw", name: "스와힐리어", label: "스와힐리어 (Swahili)" },
  { code: "mn", name: "몽골어", label: "몽골어 (Mongolian)" },
  { code: "km", name: "크메르어", label: "크메르어 (Khmer)" },
  { code: "my", name: "미얀마어", label: "미얀마어 (Burmese)" },
  { code: "ne", name: "네팔어", label: "네팔어 (Nepali)" },
  { code: "si", name: "싱할라어", label: "싱할라어 (Sinhala)" },
  { code: "ta", name: "타밀어", label: "타밀어 (Tamil)" },
  { code: "te", name: "텔루구어", label: "텔루구어 (Telugu)" },
  { code: "ka", name: "조지아어", label: "조지아어 (Georgian)" },
  { code: "hy", name: "아르메니아어", label: "아르메니아어 (Armenian)" },
  { code: "az", name: "아제르바이잔어", label: "아제르바이잔어 (Azerbaijani)" },
  { code: "kk", name: "카자흐어", label: "카자흐어 (Kazakh)" },
  { code: "uz", name: "우즈베크어", label: "우즈베크어 (Uzbek)" },
];
